import networkx as nx
import matplotlib.pyplot as plt
import os
import csv


# ================== GRAPHING LOGIC ==================
def draw_social_network(csv_file='graph.csv'):
    # 1. Create a Directed Graph (DiGraph is required for arrows)
    G = nx.DiGraph()
    
    # 2. Read the CSV file generated by C++
    if not os.path.exists(csv_file):
        print(f"Error: {csv_file} not found. Run 'xml_editor draw' first.")
        return

    print(f"Reading {csv_file}...")
    try:
        with open(csv_file, 'r') as f:
            reader = csv.reader(f)
            for row in reader:
                if len(row) >= 2:
                    # Logic: row[0] follows row[1]
                    # Arrow will point FROM Source TO Target
                    source, target = row[0], row[1]
                    G.add_edge(source, target)
    except Exception as e:
        print(f"Error reading CSV: {e}")
        return

    if G.number_of_nodes() == 0:
        print("Graph is empty.")
        return

    # 3. Setup the Drawing Style
    plt.figure(figsize=(12, 10)) # Large window
    
    # "Spring Layout" spreads nodes apart so arrows are visible
    # k=0.8 increases the distance between nodes (prevents crowding)
    pos = nx.spring_layout(G, k=0.8, iterations=50) 
    
    # A. Draw Nodes (Blue Circles)
    nx.draw_networkx_nodes(G, pos, 
                           node_size=2500, 
                           node_color='#6495ED', # Cornflower Blue
                           edgecolors='black')   # Black border around circle

    # B. Draw Labels (The ID Numbers inside the dots)
    nx.draw_networkx_labels(G, pos, 
                            font_size=14, 
                            font_family='sans-serif',
                            font_weight='bold',
                            font_color='white')

    # C. Draw Edges with ARROW HEADS
    nx.draw_networkx_edges(G, pos, 
                           width=2, 
                           arrows=True,          # Force arrows on
                           arrowstyle='-|>',     # Triangle shape pointing to target
                           arrowsize=30,         # Large size for visibility
                           edge_color='gray',
                           min_source_margin=25, # Start line away from center of source node
                           min_target_margin=25, # End line at border of target node
                           connectionstyle="arc3,rad=0.1") # Curve lines slightly

    # 4. Finalize and Show
    plt.title("Social Network Graph", fontsize=16)
    plt.axis('off') 
    
    current_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(current_dir, "..", "data")
    data_dir = os.path.abspath(data_dir)
    
    # Save to file
    output_img = os.path.join(data_dir, f"Social Network Analysis python.png")
    # output_img = "social_network_plot.png"
    plt.savefig(output_img, format="PNG", dpi=300) 
    print(f"Python Graph saved to {output_img}")
    
    plt.title("Social Network Analysis", fontsize=15)
    plt.axis('off')
    plt.show()
